
---
title: "ht5 naive bayes"
output: html_document
date: "2023-03-17"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#Librerias a utilizar
library(e1071)
library(tidyverse)
#base de datos a utilzar
db<-read.csv(file.choose())
```


###  2. Elabore un modelo de bayes ingenuo (naive bayes) utilizando el conjunto de entrenamiento.

```{r }
#Encontramos los percentiles
percentil <- quantile(db$SalePrice)
#Percentiles
estado<-c('Estado')
db$Estado<-estado
db <- within(db, Estado[SalePrice<=129975] <- 'Economica')
db$Estado[(db$SalePrice>129975 & db$SalePrice<=163000)] <- 'Intermedia'
db$Estado[db$SalePrice>163000] <- 'Cara'
#Bayes 
#Usamos el 70% de datos
porcentaje<-0.7
#El experimento debe ser repetible
set.seed(1234)
corte <- sample(nrow(db),nrow(db)*porcentaje)
#Entrenamiento
train<-db[corte,]
#Prueba
test<-db[-corte,]
```

### 3. El modelo debe ser de clasificación, use la variable categórica que hizo con el precio de las casas (barata, media y cara) como variable respuesta. 


```{r warning=FALSE}
#Entrenar el modelo
modelo<-naiveBayes(train$Estado~., data=train)
#Casting de las variables, ya que el modelo pide datos numericos
test$GrLivArea<-as.numeric(test$GrLivArea)
test$YearBuilt<-as.numeric(test$YearBuilt)
test$BsmtUnfSF<-as.numeric(test$BsmtUnfSF)
test$TotalBsmtSF<-as.numeric(test$TotalBsmtSF)
test$GarageArea<-as.numeric(test$GarageArea)
test$YearRemodAdd<-as.numeric(test$YearRemodAdd)
test$SalePrice<-as.numeric(test$SalePrice)
test$LotArea<-as.numeric(test$LotArea)
#Realizamos la prediccion
predBayes<-predict(modelo, newdata = test[,c("GrLivArea","YearBuilt","BsmtUnfSF","TotalBsmtSF","GarageArea","YearRemodAdd", "SalePrice","LotArea")])
#Convertimos la prediccion a factor
predBayes<-as.factor(predBayes)
#Creamos la matriz de confusion
cm<-caret::confusionMatrix(as.factor(predBayes),as.factor(test$Estado))
```
